apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice2
  template:
    metadata:
      labels:
        app: myservice2
    spec:
      containers:
        - image: spadarogian/myservice2:2
          imagePullPolicy: IfNotPresent
          name: myservice2
          env:
            - name: SERVICE_URL
              value: http://myservice:8080
      restartPolicy: Always